---
# This role will install and run nomad
- name: Download and extract Nomad if needed
  unarchive:
    src: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: /usr/bin
    creates: "nomad_{{ nomad_version }}_linux_amd64.zip"
    remote_src: yes

- name: Create nomad user
  user:
    name: nomad
    home: /etc/nomad.d
    system: yes
    shell: /usr/bin/false
    state: present

- name: Create data directory
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    mode: 0755

- name: Copy config
  template:
    src: "nomad.hcl.j2"
    dest: "/etc/nomad.d/nomad.hcl"
    owner: nomad
    group: nomad
    mode: 0644

- name: Systemd file for nomad
  template: 
   src: nomad.service.j2
   dest: /etc/systemd/system/nomad.service
   mode: 0644
   force: yes  

- name: Start nomad service
  systemd:
    name: nomad
    state: restarted
    daemon_reload: yes
    enabled: yes