---
- name: playbook for server vm
  hosts: servers
  become: yes

  roles:
    - role: software/consul

- name: playbook for node vm
  hosts: nodes
  become: yes

  roles:
    - role: software/consul
    - role: software/docker